server:
  port: 8081

spring:
  application:
    name: pyler-user-server

  datasource:
    url: jdbc:postgresql://pyler-db:5432/pyler_db
    username: pyler
    password: Pyler!@34
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: info
    pyler: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

jwt:
  client:
    enabled: true # Jwt Interceptor 사용
  server:
    url: http://pyler-jwt-server:8080