server:
  port: 8080

spring:
  application:
    name: plyer-jwt-server

  datasource:
    url: jdbc:postgresql://pyler-db:5432/pyler_db
    username: pyler
    password: Pyler!@34
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  data:
    redis:
      host: pyler-redis
      port: 6379

logging:
  level:
    root: info
    pyler: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

jwt:
  secret: "1gLZ1X2OE7duZXteWrGSjD8peLgX3fqqLl7YFRW5yuHKwMayX1DI40rBl8w6cSTJuKprAw84McZPWikhGdk9XQ=="